name: Build release images

on:
  pull_request:
    paths:
      - .github/workflows/release.yaml
      - 'release/**'
      - 'shared/**'
  push:
    branches:
      - 'main'
    paths:
      - .github/workflows/release.yaml
      - '.monitor/volta/RELEASES.md.last-sync'
      - 'release/**'
      - 'shared/**'

env:
  PLATFORMS: |
    linux/amd64
    linux/aarch64

jobs:
  build-release-ubuntu:
    runs-on: ubuntu-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ secrets.DOCKERCLOUD_BUILDER }}
          platforms: ${{ env.PLATFORMS }}
          install: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: release/Dockerfile-ubuntu
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ github.repository }}:latest
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}

  build-release-alpine:
    runs-on: ubuntu-release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: ${{ secrets.DOCKERCLOUD_BUILDER }}
          platforms: ${{ env.PLATFORMS }}
          install: true

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: release/Dockerfile-alpine
          platforms: ${{ env.PLATFORMS }}
          tags: |
            ${{ github.repository }}:alpine

          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry,push=true' }}
